### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by froboy** [palantirnet/drupal-skeleton#90]
Greetings!

I'd like to adapt some portions of this project into our local environment setup, but there's no LICENSE to specify usage rights like https://github.com/palantirnet/the-build has. If this repo is covered under the same license, it'd be great for that to be stated.

Thanks! 

P.S. 👋

**Comment by becw** [comment]
Hi!!

As you saw, I added licenses to the-build and the-vagrant, but didn't here, since I need to figure out how to MIT license this skeleton, without that license carrying over to projects created with this template. Maybe I'll throw in the license file and just add a setup step to manually remove it.

**Comment by becw** [comment]
Done!
